### ISSUE TITLE
hello,dear,Can you share the BraTS2022 dataset，I can't find it anywhere on the Internet. Thank you very much!

### ISSUE THREAD

**Issue by a987042035** [Arksyd96/synthesis-with-slice-based-ldm#1]
hello,dear,Can you share the BraTS2022 dataset，I can't find it anywhere on the Internet. Thank you very much!

**Comment by Arksyd96** [comment]
Hello,

I realized that I made an error in my paper; I used BraTS2021 instead of BraTS2022. This will be corrected in the arXiv version of the paper.

Here is the link to BraTS2021: [BraTS2021 on Kaggle](https://www.kaggle.com/datasets/dschettler8845/brats-2021-task1?select=BraTS2021_Training_Data.tar).

**Comment by 2ZiZ2** [comment]
Hi, there is a lot of BraTS2021 data out there, so how do you work with the data once you have downloaded it? For example, as mentioned in the article: FLAIR modal and WT area in one file? And then the segmented plots are put there?

**Comment by 2ZiZ2** [comment]
# train_dir = ‘dataset/first_stage_dataset_192x192.npy’,


What should I do with the dataset and how should the store first_stage_dataset_192x192.npy match the code?

**Comment by Arksyd96** [comment]
``first_stage_dataset_192x192.npy`` is an numpy array of shape [N, C, W, H, D]. For instance here, WxH=192x192.
The channels axis contains the modalities and the segmentation mask. Each of the modalities and the mask have to be normalized between -1 and 1. Make sure also the mask is the last channel of the array.

This allows me to load all the data into the memory at once, and avoid repetetive preprocessing at each training.

**Comment by 2ZiZ2** [comment]
Thanks for getting back to me in a timely manner!
train_dir = ‘. /data/second_stage_dataset_192x192.npy',
Can you tell me if second_stage and first_stage have the same dataset?

**Comment by 2ZiZ2** [comment]
What should I do with the dataset and how should the store second_stage_dataset_192x192.npy match the code?

**Comment by 2ZiZ2** [comment]
> 你好，亲爱的，你能分享一下 BraTS2022 数据集吗，我在互联网上的任何地方都找不到它。谢谢！
hello~What should I do with the dataset and how should the store second_stage_dataset_192x192.npy match the code?

Can you tell me ?please~~thanks~~

**Comment by Arksyd96** [comment]
Simply, the first_stage_dataset is a dataset that is trained on 2D images, which is a numpy array of shape [N * D, C, W, H].
It corresponds to the 3D MRI volumes deconstructed as 2D slices (you can remove the excessive number of black slices).

The second_stage_dataset is just the whole 3D MRI volumes dataset. Its shape is [N, C, W, H, D].

Both normalized between -1 and 1, and the radiomics pour the conditionning are stored in another .npy file. You can extract those using PyRadiomics and rearrange them as a .npy too.

**Comment by 2ZiZ2** [comment]
Thank you for your reply, could you make the processed dataset publicly available along with the radiomics of the injected conditions?
Thank you very much!
Or drop it to my email: nliing@163.com

**Comment by 2ZiZ2** [comment]
> 简单地说，first_stage_dataset 是一个在 2D 图像上训练的数据集，它是一个形状为 [N * D， C， W， H] 的 numpy 数组。它对应于解构为 2D 切片的 3D MRI 体积（您可以去除过多的黑色切片）。
> 
> second_stage_dataset只是整个 3D MRI 体积数据集。它的形状是 [N， C， W， H， D]。
> 
> 两者都在 -1 和 1 之间归一化，并且注入条件的放射组学存储在另一个 .npy 文件中。您可以使用 PyRadiomics 提取它们，并将它们重新排列为 .npy。
What about when I follow your code for data processing and run it after processing the second part of the complete 3DMRI, resulting in a dimensional mismatch?

**Comment by Arksyd96** [comment]
Hello 2ZiZ2,

Unfortunately, it has been almost a year since i've worked on this project. Most of the preprocessing scripts i've written were on notebooks, since those were small scripts only. I do not have the preprocessed data anymore. Since those are public, i judged that its not necessary to keep them.

I can suggest you is to use the scripts found in ./preprocessing_scripts/ which allows you to reproduce the first_stage_dataset and second_stage_dataset .npy files. It takes as input the path to the root BRATS2021 directory.
